### ISSUE TITLE
Support parsing ```plantuml code block in markdown

### ISSUE THREAD

**Issue by chuxubank** [gmunguia/markdown-it-plantuml#11]
`vscode-plantuml` gives a way to preview plantuml in markdown in vscode. [See here](https://github.com/qjebbs/vscode-plantuml#markdown-integrating)

![](https://raw.githubusercontent.com/qjebbs/vscode-plantuml/master/images/markdown_demo.png)

It will be a nice thing to support this feature because there is no need to delete ` ```plantuml ... ``` ` when deploy a site.

**Comment by gmunguia** [comment]
Thanks for creating an issue! I am really busy right now. I will have a look at this in a week or so.

**Comment by gmunguia** [comment]
Markdown uses ``` to display source code. To me, it is really weird how that plugin uses ``` to actually run the code. After a bit of though, I am not going to integrate this in the library, sorry =(

**Comment by chuxubank** [comment]
Actually not only `vscode-plantuml` run the code, in `Typora` many other diagram plugins also run the code  lol, such as `Sequence`, `Flowchart` and `Mermaid`. [See here](https://support.typora.io/Draw-Diagrams-With-Markdown/)

**Comment by mmngreco** [comment]
Ohhh it's a pity! Also Gitlab uses this behaviour: 
https://docs.gitlab.com/ce/administration/integration/plantuml.html

**Comment by Hipska** [comment]
Yes indeed, please reopen this issue. This syntax is much more clean and compatible with other markdown parsers.

**Comment by manastalukdar** [comment]
Agree, for sake of consistency with other markdown parsers, please consider reopening this issue.

**Comment by manastalukdar** [comment]
I ended up writing some custom code to use fenced blocks

```
```plantuml
```

as markers. The source code of this plugin was helpful to understand how Markdown-it plugins work, so thanks to the original author.

**Comment by gossi** [comment]
I use this config:

```js
const config = {
  openMarker: '```plantuml',
  closeMarker: '```'
}
```

I'd also rather see the fenced version as default, as this allows indentation (which can be very helpful). Anyway regular markdown would treat indentation as code blocks.

**Comment by jaune162** [comment]
@gossi 
This config conflict with hexo's built-in highlighter. Maybe it's not possible to use code blocks for rendering in hexo
