### ISSUE TITLE
[Feature Request] Change plantuml url address to https?

### ISSUE THREAD

**Issue by dillionverma** [gmunguia/markdown-it-plantuml#15]
https://github.com/gmunguia/markdown-it-plantuml/blob/master/index.js#L10

This url can be changed to https and everything should still work normally. 

This feature is needed so that I can use this plugin on my site and my site will remain secure.

**Comment by gmunguia** [comment]
Thanks for bringing that up! I have changed the default URL to HTTPS. It is already available in v1.4.0 of the package.
