### ISSUE TITLE
export PDF

### ISSUE THREAD

**Issue by VerenaHo** [gmunguia/markdown-it-plantuml#16]
Wenn using the preview panel you need following tags to see the plantuml 
```´
````plantuml
[someNiceUML]
````

for the PDF export you need 
@startuml
[someNiceUML]
@enduml

is there a way to print/see the UML in both not in either the preview or the export

**Comment by SoerenSoegaard** [comment]
This seems to work for me (start with "```plantuml" - end with "```")

```
```plantuml
@startuml
Baan -> SHARK: Purchase order with inspection (EFD302)
SHARK <- Operator: Receives the goods
SHARK <- Operator: Store the Goods
SHARK -> Baan: sp:Document_MakeOrderLineReceived > file:EFD351..fi
Baan -> SHARK: file:EFD351..fbk > sp:SharkLink_EFD_351
SHARK -> Baan: Document(OrderAckEFD) > EFD361..fi
@enduml
 ```
```
Settings:

    "markdown-pdf.plantumlOpenMarker": "```plantuml",
    "markdown-pdf.plantumlCloseMarker": "```",

**Comment by gmunguia** [comment]
I'm not sure what this "preview panel" is. Maybe related to https://github.com/gmunguia/markdown-it-plantuml/issues/12?
