### ISSUE TITLE
Support fragments and includes

### ISSUE THREAD

**Issue by chbndrhnns** [gmunguia/markdown-it-plantuml#17]
I am wondering if there is any way to support reusable elements in PlantUML diagrams as described at https://mrhaki.blogspot.com/2016/12/plantuml-pleasantness-include-partial.html?

**Comment by gmunguia** [comment]
Generating the image from the diagram is delegated to the `server` (see https://github.com/gmunguia/markdown-it-plantuml#advanced-usage). Customising how the image is generated is out of scope of this project.
