### ISSUE TITLE
Online plantuml did not support chinese

### ISSUE THREAD

**Issue by purocean** [gmunguia/markdown-it-plantuml#3]
Can support use local plantuml ?
![image](https://user-images.githubusercontent.com/7115690/33652306-d9ccdf44-daa3-11e7-9216-dae5ca11043e.png)

**Comment by gmunguia** [comment]
Hi! Thanks your using this plugin =)

It should be possible to do what you want using the `generateSource` option:
```
function customSrcGenerator (umlCode) { 
    return 'http://your-server/plant-uml-generator/' + yourHashFunction(umlCode); 
}

var md = require('markdown-it')()
    .use(require('markdown-it-plantuml'), { generateSource: customSrcGenerator });
```

Let me know how it goes!
