### ISSUE TITLE
Make plantuml server url configurable

### ISSUE THREAD

**Issue by chbndrhnns** [gmunguia/markdown-it-plantuml#5]
In case I would like to use a private instance of a plantuml server, I would like to be able to configure the markdown plugin to use a custom URL.

**Comment by gmunguia** [comment]
Hi! Thanks your using this plugin =)

It should be possible to do what you want using the `generateSource` option:
```
function customSrcGenerator (umlCode) { 
    return `https://your.server/plant-uml/${yourEncodeFunction(umlCode)}`; 
}

var md = require('markdown-it')()
    .use(require('markdown-it-plantuml'), { generateSource: customSrcGenerator });
```

Let me know how it goes!

**Comment by chbndrhnns** [comment]
I wanted to suggest this feature to the Boostnote IO developers and now I posted your example to the corresponding issue. 

https://github.com/BoostIO/Boostnote/issues/1592

**Comment by gmunguia** [comment]
Great! I have updated the docs to include the example.
